photobattle/urls.py
from django.urls import path
from . import views

app_name = "photobattle"

urlpatterns = [
    path("", views.landing, name="landing"),
    path("battle/<code>/manage", views.manage_battle, name="manage_battle"),
    path("battle/<code>", views.view_battle, name="view_battle"),
    path("profile", views.view_profile, name="view_profile"),
    path("api", views.api, name="api"),
]

photobattle/templates/photobattle/base.html
{% load static %}

<!DOCTYPE html>

<html lang="fr">

<head>
    <title>{% block title %}Joutes photographiques{% endblock title %}</title>
    {% block head %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/gh/ychalier/pifekit/pifekit.min.css" />
    <script type="text/javascript" src="https://cdn.jsdelivr.net/gh/ychalier/pifekit/pifekit.min.js"></script>
    <link rel="stylesheet" href="{% static 'photobattle/style.css' %}" />
    {% endblock head %}
</head>

<body class="dark-blue noise">
    {% block body %}
    <div class="columns">
        <div class="column col-4 col-xl-3 col-lg-2 hide-md"></div>
        <div class="column col-4 col-xl-6 col-lg-8 col-md-12 col-sm-12 col-xs-12">
        {% block center_column %}
                {% comment %}
                <header class="navbar navbar-float container">
                    <section class="navbar-section">
                        <a href="{% url 'photobattle:landing' %}" class="navbar-brand mr-2">Joutes photographiques</a>
                    </section>
                    {% if request.user.is_authenticated %}
                    <section class="navbar-section">
                        <a href="{% url 'photobattle:view_profile' %}" class="btn btn-link" title="Vos défis"><i class="icon icon-people"></i></a>
                    </section>
                    {% endif %}
                </header>
                {% endcomment %}
                <div>{% block main_content %}{% endblock main_content %}</div>
        {% endblock center_column %}
        </div>
        <div class="column col-4 col-xl-3 col-lg-2 col-md-12 col-sm-12 col-xs-12 p-relative"><div class="hide-md" style="height: 4.2rem"></div>{% block right_column %}{% endblock right_column %}</div>
    </div>
    <footer class="columns mb-4">
        <div class="column col-4 col-xl-6 col-lg-8 col-md-12 col-sm-12 col-xs-12 container">
            <hr>
            Développé et maintenu par <a href="https://chalier.fr/">Yohan Chalier</a>
            {% if request.user.is_authenticated %}
             &mid; 
            <a href="{% url 'photobattle:view_profile' %}" title="Vos concours"><i class="icon icon-people"></i> Vos concours</a>
            {% endif %}
        </div>
    </footer>
    {% endblock body %}
    {% block body_scripts %}{% endblock body_scripts %}
</body>

</html>

photobattle/templates/photobattle/battle.html
{% extends "photobattle/base.html" %}
{% load static %}


{% block title %}{{ battle.title }}{% endblock %}

{% block head %}
{{ block.super }}
<script src="{% static 'photobattle/preview.js' %}"></script>
{% endblock head %}

{% block main_content %}

<h1>{{ battle.title }}</h1>

<p>
    {% if battle.state == 'I' %}
    Les inscriptions sont ouvertes !
    {% elif battle.state == 'U' %}
    <button class="btn btn-primary" onclick="showModal('modal-upload')">Partager une photo</button>
    {% elif battle.state == 'V' %}
    <button class="btn btn-primary" onclick="showModal('modal-vote-team')">Voter</button>
    {% elif battle.state == 'C' %}
    Ce concours est terminé.
    {% endif %}
    {% if is_owner %}&nbsp;<a href="{% url 'photobattle:manage_battle' battle.code %}">Gérer</a>{% endif %}
</p>

{% if battle.state == "I" %}

    <h2>Équipes</h2>

    {% if battle.teams.count %}
    <ul>
    {% for team in battle.teams.all %}
    <li>{{ team.name }}</li>
    {% endfor %}
    </ul>
    {% else %}
    <div class="empty">
        <div class="empty-icon">
            <i class="icon icon-people icon-2x"></i>
        </div>
        <p class="empty-title">Aucune équipe inscrite</p>
    </div>
    {% endif %}

{% elif battle.state == "U" %}

{% for team, photos in battle.photos_by_team.items %}
<h5>{{ team.name }} ({{ photos | length }}/{{ battle.photo_count }})</h5>
<p>
    {% if photos %}
    {% for photo in photos %}
    <img src="{% static 'photobattle/dummy_image.jpg' %}" />
    {% endfor %}
    {% else %}
    <span class="text-gray">Aucune photo n'a encore été partagée.</span>
    {% endif %}
</p>
{% endfor %}

{% elif battle.state == "V" %}

<p>
    {% for photo in battle.photos_shuffled %}
    <a href="{{ photo.url }}" class="preview" preview-img="{{ photo.url }}"><img src="{{ photo.url_thumbnail }}" /></a>
    {% endfor %}
</p>

<p>
    Vote{{ battle.votes.count | pluralize }} reçu{{ battle.votes.count | pluralize }} : <span>{{ battle.votes.count }}</span>
</p>

{% elif battle.state == "C" %}

<h2>Classement</h2>

{% for result in battle.results.all %}
{% if result.rank == 1 %}
<i class="icon icon-trophy" style="color: gold"></i>
{% elif result.rank == 2%}
<i class="icon icon-trophy" style="color: silver"></i>
{% elif result.rank == 3%}
<i class="icon icon-trophy" style="color: #A77044"></i>
{% endif %}
&nbsp;
{{ result.team.name }}
<br>
{% endfor %}

<h2>Photos</h2>

<p class="grid">
    {% for photo in battle.photos_ranked %}
    <a href="{{ photo.url }}" class="tooltip preview" preview-img="{{ photo.url }}" data-tooltip="{{ photo.team.name }} {% if photo.grade_scaled >= 1 %}★{% else %}☆{% endif %}{% if photo.grade_scaled >= 2 %}★{% else %}☆{% endif %}{% if photo.grade_scaled >= 3 %}★{% else %}☆{% endif %}{% if photo.grade_scaled >= 4 %}★{% else %}☆{% endif %}{% if photo.grade_scaled >= 5 %}★{% else %}☆{% endif %}"><img src="{{ photo.url_thumbnail }}" /></a>
    {% endfor %}
</p>

{% endif %}

<div class="modal" id="modal-upload">
    <span class="modal-overlay" onclick="closeModal('modal-upload')"></span>
    <div class="modal-container">
        <div class="modal-header">
            <div class="modal-title h5">Partager une photo</div>
        </div>
        <div class="modal-body">
            <div class="form-group">
                <label class="form-label" for="upload-select-team">Sélectionnez votre équipe</label>
                <select class="form-select" id="upload-select-team" name="team">
                    {% for team in battle.teams.all %}
                    <option value="{{ team.id }}">{{ team.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label class="form-label" for="upload-input-image">Sélectionnez une image</label>
                <input class="form-input" id="upload-input-image" type="file" name="image" accept=".jpg,.jpeg,.png,.gif,.tiff" />
            </div>
        </div>
        <div class="modal-footer">
            <button class="btn btn-primary" id="btn-upload-submit">Envoyer</button>
        </div>
    </div>
</div>

<div class="modal" id="modal-progress">
    <span class="modal-overlay"></span>
    <div class="modal-container">
        <div class="modal-header">
            <div class="modal-title h5">Téléversement en cours…</div>
            <div class="modal-subtitle" id="modal-progress-label"></div>
        </div>
        <div class="modal-body">
            <progress class="progress" id="modal-progress-progress" value="0" max="3"></progress>
        </div>
    </div>
</div>

<div class="modal" id="modal-vote-team">
    <span class="modal-overlay" onclick="closeModal('modal-vote-team')"></span>
    <div class="modal-container">
        <div class="modal-header">
            <div class="modal-title h5">Sélectionnez votre équipe</div>
        </div>
        <div class="modal-body">
            {% for team in battle.teams.all %}
            <button class="btn modal-vote-team-button" team="{{ team.id }}">{{ team.name }}</button>
            {% endfor %}
        </div>
    </div>
</div>

<div class="modal modal-xl" id="modal-vote-rank">
    <input hidden id="modal-vote-rank-team" name="team" value="" />
    <span class="modal-overlay" onclick="closeModal('modal-vote-rank')"></span>
    <div class="modal-container">
        <div class="modal-header">
            <div class="modal-title h5">Classez les photos par ordre de préférence</div>
            <div class="modal-subtitle">En premier (en haut à gauche) celle que vous aimez le moins, en dernier (en bas à droite) celle que vous aimez le plus</div>
        </div>
        <div class="modal-body">
            <div>
            {% for photo in battle.photos_shuffled %}
            <span class="photo-wrapper" draggable team="{{ photo.team.id }}" photo="{{ photo.id }}"><a href="{{ photo.url }}"><img src="{{ photo.url_thumbnail }}" /></a></span>
            {% endfor %}
            </div>
        </div>
        <div class="modal-footer">
            <button class="btn btn-primary" id="modal-vote-rank-button">Voter</button>
        </div>
    </div>
</div>

{% endblock main_content %}

{% block body_scripts %}
<script>
const API_URL = "{% url 'photobattle:api' %}";
const BATTLE_ID = "{{ battle.id }}";
const CSRF_TOKEN = "{{ csrf_token }}";
{% if battle.state == 'U' %}const IMGBB_APIKEY = "{{ imgbb_apikey }}";{% endif %}
</script>
<script src="{% static 'photobattle/battle.js' %}"></script>
{% comment %}
<script>
    var elem = document.querySelector(".grid");
    var msnry = new Masonry(elem, {
        itemSelector: ".grid-item",
        columnWidth: 200
    });
    var msnry = new Masonry(".grid", {});
</script>
{% endcomment %}
{% endblock body_scripts %}

photobattle/templates/photobattle/landing.html
{% extends "photobattle/base.html" %}

{% block main_content %}

<h1>Joutes photographiques</h1>

<p>
    Trois équipes se donnent rendez-vous avant le coucher du soleil.
    Elles ont deux heures pour prendre des photos, et retourner au point de départ.
    Elles ont ensuite 24h pour développer ces photos et les partager.
    Chaque participant vote pour évaluer les photos au jugement majoritaire.
    L'équipe perdante a un gage.
    Attention, si une équipe se présente en retard au rendez-vous final,
    elle est déclarée perdante.
</p>

<p>
    Inspiré par la série « <i>Photo-Battle</i> » de Hayden Pedersen :
    <div class="video-responsive">
        <iframe src="https://www.youtube-nocookie.com/embed/C8oLi-ZCqns" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>
</p>

{% endblock main_content %}

photobattle/templates/photobattle/manage_battle.html
{% extends "photobattle/base.html" %}

{% block title %}{{ battle.title }}{% endblock %}

{% block main_content %}

<h1>{{ battle.title }}</h1>

<p class="btn-blocks">
    <a class="btn" href="{% url 'photobattle:view_battle' battle.code %}">Voir</a>
    <a class="btn" href="{% url 'admin:photobattle_battle_change' battle.id %}">Admin</a>
</p>

<h2>État</h2>

<p>
    État actuel : <b>{{ battle.get_state_display }}</b>
</p>

{% if next_state_value and next_state_display %}
<form method="post" action="" class="my-4">
    {% csrf_token %}
    <input hidden name="action" value="change_state" />
    <input hidden name="state" value="{{ next_state_value }}" />
    <button class="btn btn-primary">Passer à l'état suivant ({{ next_state_display }})</button>
</form>
{% endif %}

<h2>Équipes</h2>

{% if battle.teams.count %}
<ul>
{% for team in battle.teams.all %}
<li>{{ team.name }} <form class="d-inline ml-4" method="post" action="">{% csrf_token %}<input type="hidden" name="action" value="remove_team"/><input type="hidden" name="team" value="{{ team.id }}"/><button class="btn btn-action"><i class="icon icon-delete"></i></button></form></li>
{% endfor %}
</ul>
{% else %}
<div class="empty">
    <div class="empty-icon">
        <i class="icon icon-people"></i>
    </div>
    <p class="empty-title h5">Aucune équipe inscrite</p>
  </div>
{% endif %}

<form method="post" action="" class="my-4">
    {% csrf_token %}
    <input hidden name="action" value="create_team" />
    <div class="input-group">
        <input class="form-input" type="text" name="team" placeholder="Les petits pédestres" />
        <input class="btn btn-primary input-group-btn" type="submit" value="Créer l'équipe" />
    </div>
</form>

<form method="post" action="" class="my-4">
    {% csrf_token %}
    <input type="text" hidden name="action" value="register_team" />
    <div class="input-group">
        <select class="form-select" name="team">
            {% for team in teams %}
            <option value="{{ team.id }}">{{ team.name }}</option>
            {% endfor %}
        </select>
        <input class="btn btn-primary input-group-btn" type="submit" value="Inscrire" />
    </div>
</form>

<h2>Photos</h2>

{% if battle.photos.count %}

{% for team, photos in battle.photos_by_team.items %}
<h5>{{ team.name }} ({{ photos | length }}/{{ battle.photo_count }})</h5>
<p>
    {% if photos %}
    {% for photo in photos %}
    <div class="popover">
        <a href="{{ photo.url }}"><img src="{{ photo.url_thumbnail }}" /></a>
        <div class="popover-container">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">Partagée le {{ photo.date_creation | date }} à {{ photo.date_creation | time }}.{% if photo.grade %}<br>Évalutation : {{ photo.grade }}{% endif %}</div>
                </div>
                <div class="card-footer">
                    <form method="post" action="">
                        {% csrf_token %}
                        <input hidden name="action" value="delete_photo" />
                        <input hidden name="photo" value="{{ photo.id }}" />
                        <button class="btn btn-primary">Supprimer</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    {% else %}
    <span class="text-gray">Aucune photo n'a encore été partagée.</span>
    {% endif %}
</p>
{% endfor %}

{% else %}
<div class="empty">
    <div class="empty-icon">
        <i class="icon icon-photo"></i>
    </div>
    <p class="empty-title h5">Aucune photo partagée</p>
  </div>
{% endif %}

<h2>Votes</h2>

{% if battle.votes.count %}
<table class="table table-hover table-striped">
<thead>
    <tr>
        <th>Équipe</th>
        <th>Date</th>
        <th>Classement</th>
        <th>Action</th>
    </tr>
</thead>
<tbody>
    {% for vote in battle.votes.all %}
    <tr>
        <td>{{ vote.team.name }}</td>
        <td>{{ vote.date_creation }}</td>
        <td>{{ vote.ranking }}</td>
        <td><form class="d-inline" action="" method="post">{% csrf_token %}<input hidden name="action" value="delete_vote" /><input hidden name="vote" value="{{ vote.id }}" /><button title="Supprimer ce vote" class="btn btn-action"><i class="icon icon-delete"></i></button></form></td>
    </tr>
    {% endfor %}
</tbody>
</table>

{% else %}
<div class="empty">
    <div class="empty-icon">
        <i class="icon icon-post"></i>
    </div>
    <p class="empty-title h5">Aucun vote émis</p>
  </div>
{% endif %}

<h2>Résultats</h2>

{% if battle.results.count %}
<ul>
{% for result in battle.results.all %}
<li>{{ result }}</li>
{% endfor %}
</ul>
{% else %}
<div class="empty">
    <div class="empty-icon">
        <i class="icon icon-trophy"></i>
    </div>
    <p class="empty-title h5">Aucun résultat calculé</p>
  </div>
{% endif %}

<br>

{% endblock main_content %}

photobattle/templates/photobattle/profile.html
{% extends "photobattle/base.html" %}

{% block title %}Vos concours{% endblock title %}

{% block main_content %}

<h1>Vos concours</h1>

{% if battles.count %}
<p>
    <button class="btn btn-primary" onclick="showModal('modal-create-battle')">Créer un nouveau concours</button>
</p>

<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Titre</th>
            <th>Crée le</th>
            <th>État</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
    {% for battle in battles %}
        <tr>
            <td><a href="{% url 'photobattle:view_battle' battle.code %}">{{ battle.title }}</a></td>
            <td>{{ battle.date_creation | date }}</td>
            <td><span class="label">{{ battle.get_state_display }}</span></td>
            <td>
                <a class="btn btn-action" href="{% url 'photobattle:manage_battle' battle.code %}" title="Gérer"><i class="icon icon-edit"></i></a>
                <form class="d-inline" method="POST" action="">{% csrf_token %}<input hidden name="action" value="delete_battle" /><input hidden name="battle" value="{{ battle.id }}" /><button class="btn btn-action" title="Supprimer"><i class="icon icon-delete"></i></button></form>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% else %}
<div class="empty">
    <div class="empty-icon">
        <i class="icon icon-post"></i>
    </div>
    <p class="empty-title h5">Vous n'avez créé aucun concours</p>
    <p class="empty-subtitle">Cliquez sur le bouton ci-dessous pour créer un nouveau concours</p>
    <div class="empty-action">
        <button class="btn btn-primary" onclick="showModal('modal-create-battle')">Créer un nouveau concours</button>
    </div>
</div>
{% endif %}

<div class="modal" id="modal-create-battle">
    <span class="modal-overlay" onclick="closeModal('modal-create-battle')"></span>
    <div class="modal-container">
        <div class="modal-header">
            <div class="modal-title h5">Créer un nouveau défi</div>
        </div>
        <form method="post" action="">
            {% csrf_token %}
            <input hidden name="action" value="create_battle" />
            <div class="modal-body">
                <div class="form-group">
                    <label class="form-label" for="input-title">Titre</label>
                    <input class="form-input" id="input-title" type="text" name="title" placeholder="Joute photographique n°2" required />
                </div>
                <div class="form-group">
                    <label class="form-label" for="input-title">Nombre de photos</label>
                    <input class="form-input" id="input-title" type="number" min="1" name="photo_count" value="3" />
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary">Créer</button>
            </div>
        </form>
    </div>
</div>

{% endblock main_content %}